# -*- coding: utf-8 -*-
"""avatar-creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2lVRPaIoftFtPPDIsBZ8GhPZFTicaU0
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

def reduce_colors(img, k):
    data = np.float32(img).reshape((-1,3))

    criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 20, 0.001)

    ret, label, center = cv2.kmeans(data, k, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
    center = np.uint8(center)
    result = center[label.flatten()]
    result = result.reshape(img.shape)
    return result

def get_edges(img, line_size, blur_val):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray_blur = cv2.medianBlur(gray, blur_val)
    edges = cv2.adaptiveThreshold(gray_blur, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, line_size, blur_val)
    return edges

img = cv2.imread("/content/2717085.jpeg")
cv2_imshow(img)

line_size=7;
blur_val=9;
edges=get_edges(img,line_size,blur_val)
cv2_imshow(edges)

k=9
img=reduce_colors(img,k)
cv2_imshow(img)

blurred=cv2.bilateralFilter(img,d=3,sigmaColor=200,sigmaSpace=200)
cv2_imshow(blurred)

cartoon=cv2.bitwise_and(blurred,blurred,mask=edges)
cv2_imshow(cartoon)